import type { FindingCategory } from '@/engine/types';

export interface DiagnosticPage {
  slug: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  symptoms: string[];
  detects: string[];
  checks: string[];
  category: FindingCategory;
}

export const diagnosticPages: DiagnosticPage[] = [
  {
    slug: 'android-reboot-analyzer',
    title: 'Android Reboot Analyzer – Watchdog, Panic and Boot Reason',
    description: 'Analyze Android bugreports for system_server watchdog, kernel panic, thermal shutdown, orderly reboot and boot-reason evidence.',
    h1: 'Android Reboot Analyzer',
    intro: 'Unexpected restarts cross framework, kernel, vendor and power layers. The analyzer separates the recovery mechanism from the evidence that happened before it.',
    symptoms: ['Random restart with no crash dialog', 'Reboot after a frozen screen', 'Restart after a system or vendor service stalls', 'Hardware feature unavailable immediately after reboot'],
    detects: ['system_server watchdog recovery', 'Boot-reason properties', 'Orderly shutdown checkpoints', 'Related kernel panic and thermal evidence', 'Storage or display failures that can precede reboot'],
    checks: ['Start from the earliest abnormal event before the restart.', 'Verify boot-reason strings against pstore/kernel and framework evidence.', 'Compare repeated incidents for the same blocked service or driver path.'],
    category: 'reboot',
  },
  {
    slug: 'android-anr-analyzer',
    title: 'Android ANR Analyzer – Input, Broadcast and Service Timeouts',
    description: 'Find Android ANR records, input-dispatch timeouts and nearby binder, CPU, memory and I/O evidence.',
    h1: 'Android ANR Analyzer',
    intro: 'The final timeout line only proves that a deadline was missed. Useful diagnosis starts with the affected process, timeout type and the thread or system resource that stopped making progress.',
    symptoms: ['App freezes before an ANR dialog', 'Touch stops responding', 'Broadcast or service timeout', 'System app becomes unresponsive under load'],
    detects: ['ANR in process records', 'Input dispatch timeouts', 'Broadcast/service timeout markers', 'Nearby system-pressure findings', 'Historical ANR traces when present in the ZIP'],
    checks: ['Inspect the matching /data/anr/anr_* trace.', 'Check main-thread locks, binder waits, storage I/O and scheduling state.', 'Use PSI and lmkd evidence to rule in or out system-wide pressure.'],
    category: 'anr',
  },
  {
    slug: 'android-crash-analyzer',
    title: 'Android Crash Analyzer – Java, Native and Tombstone Triage',
    description: 'Analyze Android logs for fatal exceptions, native signals, tombstones, abort messages and crash context.',
    h1: 'Android Crash Analyzer',
    intro: 'Java exceptions and native crashes need different evidence. The analyzer keeps the process, exception/signal and nearby source lines together so the next debugging step is explicit.',
    symptoms: ['App closes unexpectedly', 'System component repeatedly restarts', 'Vendor/native service dies', 'Fatal exception or signal appears in logcat'],
    detects: ['FATAL EXCEPTION and process context', 'Native fatal signal records', 'Tombstone entries in bugreport ZIPs', 'Abort message and nearby backtrace context'],
    checks: ['For Java, follow the deepest useful cause and first owned frame.', 'For native, preserve signal, fault address, abort message and BuildId.', 'Symbolize only against the exact build.'],
    category: 'crash',
  },
  {
    slug: 'android-kernel-panic-analyzer',
    title: 'Android Kernel Panic Analyzer – Panic, RCU Stall and Hung Task',
    description: 'Detect Android kernel panic, oops, hung task, lockup, RCU stall and pstore/ramoops evidence.',
    h1: 'Android Kernel Panic Analyzer',
    intro: 'Abrupt resets often leave their strongest evidence outside normal framework logs. Previous-boot pstore/ramoops and the first kernel call trace deserve priority.',
    symptoms: ['Sudden reboot with little framework evidence', 'Complete device freeze', 'Watchdog reset under hardware load', 'Repeated driver instability'],
    detects: ['Kernel panic and oops markers', 'Soft/hard lockups', 'Hung-task warnings', 'RCU stalls', 'Previous-boot kernel artifacts when included'],
    checks: ['Capture pstore/ramoops whenever available.', 'Find the first faulting stack before secondary warnings.', 'Match kernel/vendor module symbols to the exact build.'],
    category: 'kernel',
  },
  {
    slug: 'android-battery-wakelock-analyzer',
    title: 'Android Battery and Wakelock Analyzer – BatteryStats Triage',
    description: 'Inspect Android bugreports for long partial wake locks, repeated wake reasons, jobs and sync activity using BatteryStats evidence.',
    h1: 'Android Battery / Wakelock Analyzer',
    intro: 'Battery analysis is about time attribution, not a single “high usage” number. This analyzer starts with long wake locks and dense wake/job/sync activity, then points you back to the observation window.',
    symptoms: ['Battery drains while screen is off', 'Device stays awake unexpectedly', 'Frequent background jobs or syncs', 'Standby drain after a feature is no longer active'],
    detects: ['Long partial wake-lock records', 'Battery-history longwake markers', 'Dense wake/job/sync transitions', 'Correlation with network and thermal findings'],
    checks: ['Identify UID/package and wake-lock name.', 'Compare wake time against the actual BatteryStats collection window.', 'Check whether screen-off periods still contain CPU, radio, job or sync bursts.'],
    category: 'battery',
  },
  {
    slug: 'android-memory-pressure-analyzer',
    title: 'Android Memory Pressure Analyzer – lmkd, OOM and PSI',
    description: 'Find lmkd kills, OutOfMemoryError, kernel OOM and memory-pressure evidence in Android bugreports.',
    h1: 'Android Memory Pressure Analyzer',
    intro: 'A process kill is not automatically a memory leak. The useful distinction is normal cached-process reclamation versus sustained pressure that kills important work or destabilizes the system.',
    symptoms: ['Apps restart when switching tasks', 'ANRs during heavy multitasking', 'System services disappear under memory load', 'Java or native allocations fail'],
    detects: ['lmkd / low-memory kills', 'Java OutOfMemoryError', 'Kernel OOM / page allocation failures', 'Links to ANR, crash and binder failures'],
    checks: ['Inspect meminfo, PSI, zram/swap and large PSS/RSS consumers.', 'Check whether foreground/system processes are being killed.', 'Look for growth over time rather than one isolated snapshot.'],
    category: 'memory',
  },
  {
    slug: 'android-binder-analyzer',
    title: 'Android Binder Analyzer – Failed Transactions and Dead Services',
    description: 'Detect FAILED BINDER TRANSACTION, DeadObjectException, TransactionTooLargeException and binder allocation errors.',
    h1: 'Android Binder IPC Analyzer',
    intro: 'Binder errors can be the root cause or only a consequence of a dead/stalled service. The analyzer surfaces transaction failures and correlates them with ANRs, memory pressure and service crashes.',
    symptoms: ['System or app hangs during IPC', 'DeadObjectException', 'TransactionTooLargeException', 'Vendor service dies and clients start failing'],
    detects: ['FAILED BINDER TRANSACTION', 'binder_alloc failures', 'DeadObjectException', 'TransactionTooLargeException', 'Cross-links to ANR/display/biometric findings'],
    checks: ['Inspect the sender and target process when binder logs provide them.', 'For dead objects, locate the target service death first.', 'For large transactions, reduce the payload rather than retrying.'],
    category: 'binder',
  },
  {
    slug: 'android-storage-io-analyzer',
    title: 'Android Storage I/O Analyzer – UFS, eMMC, ext4 and f2fs Errors',
    description: 'Find Android block I/O, UFS/eMMC, ext4/f2fs and dm-verity errors that can cause ANR, reboot or boot failure.',
    h1: 'Android Storage / Filesystem Analyzer',
    intro: 'Storage faults often look like higher-layer freezes. A blocked filesystem or failing UFS/eMMC path can trigger ANRs, service timeouts and watchdog recovery far above the original error.',
    symptoms: ['Long UI freezes during I/O', 'Boot failure after filesystem errors', 'Watchdog during storage-heavy work', 'Read-only remount or verified-boot error'],
    detects: ['Block I/O errors', 'UFS/eMMC timeout/fatal records', 'ext4/f2fs corruption warnings', 'dm-verity failures', 'Read-only remount evidence'],
    checks: ['Identify device/partition and first error.', 'Inspect latency and filesystem recovery messages around the same time.', 'Treat integrity failures before debugging downstream app errors.'],
    category: 'storage',
  },
  {
    slug: 'android-fingerprint-log-analyzer',
    title: 'Android Fingerprint Log Analyzer – HAL, Binder and UDFPS',
    description: 'Analyze Android bugreports for fingerprint HAL failures, biometric service errors, UDFPS and display coordination problems.',
    h1: 'Android Fingerprint / UDFPS Analyzer',
    intro: 'Fingerprint is a chain: framework service, provider/HAL, vendor process, sensor and—for UDFPS—the display pipeline. A useful report correlates those layers instead of grepping “fingerprint”.',
    symptoms: ['Fingerprint stops working after reboot', 'Biometric prompt reports hardware unavailable', 'UDFPS area does not brighten correctly', 'Fingerprint HAL/vendor service dies'],
    detects: ['Biometric/FingerprintService failures', 'HAL or binder death markers', 'UDFPS/HBM-related failures', 'Related display and SELinux evidence'],
    checks: ['Check provider/HAL lifecycle and binder reconnection.', 'For UDFPS, correlate local-HBM/brightness and composer events.', 'Separate transient initialization delay from persistent sensor/driver failure.'],
    category: 'biometric',
  },
  {
    slug: 'android-display-log-analyzer',
    title: 'Android Display Log Analyzer – SurfaceFlinger, HWC, DRM and Panel',
    description: 'Find SurfaceFlinger, hardware composer, DRM, DSI/panel and DisplayManager failures in Android bugreports.',
    h1: 'Android Display Pipeline Analyzer',
    intro: 'A black or frozen screen can originate in app rendering, SurfaceFlinger, vendor composer or the kernel display driver. The first failing layer matters.',
    symptoms: ['Black/frozen screen', 'UI stops updating', 'Display recovers only after reboot', 'UDFPS illumination or HBM fails'],
    detects: ['SurfaceFlinger errors/timeouts', 'Composer/HWC service failures', 'DisplayManager failures', 'DRM/DSI/panel errors'],
    checks: ['Find the earliest display-layer error.', 'Check composer service and binder health.', 'Inspect kernel DRM/panel logs when userspace is waiting on hardware.'],
    category: 'display',
  },
  {
    slug: 'android-thermal-log-analyzer',
    title: 'Android Thermal Analyzer – Throttling and Thermal Shutdown',
    description: 'Analyze Android logs for critical thermal status, throttling, emergency shutdown and heat-related instability.',
    h1: 'Android Thermal Analyzer',
    intro: 'High temperature alone is weak evidence. The useful distinction is normal throttling versus an explicit severe/critical policy state or thermal shutdown.',
    symptoms: ['Device powers off under load', 'Performance falls sharply while hot', 'Restart during charging/GPU load', 'Thermal warnings occur before instability'],
    detects: ['Thermal emergency/shutdown markers', 'Severe throttling state', 'Correlation with battery/reboot evidence'],
    checks: ['Identify thermal zone and sensor.', 'Map the event to charging, modem, CPU/GPU and display workload.', 'Confirm whether shutdown was orderly or another reset occurred.'],
    category: 'thermal',
  },
  {
    slug: 'android-network-log-analyzer',
    title: 'Android Network Log Analyzer – Wi-Fi, DNS, Netd and Data Stalls',
    description: 'Find Android connectivity validation, DNS, Wi-Fi, netd and data-stall errors in bugreports.',
    h1: 'Android Network / Connectivity Analyzer',
    intro: 'Network logs are noisy. The analyzer focuses on explicit validation, DNS, link, netd and data-stall failures and treats them as meaningful only when they line up with the outage window.',
    symptoms: ['Internet disappears while link still appears connected', 'Repeated Wi-Fi disconnects', 'DNS timeouts', 'Mobile data stall or validation failure'],
    detects: ['Data-stall markers', 'Network validation failures', 'DNS resolver errors', 'Wi-Fi/netd failure records'],
    checks: ['Identify active transport/network at the incident time.', 'Separate link loss from DNS/validation failure.', 'Check firmware/service resets and repeated radio wakeups.'],
    category: 'network',
  },
  {
    slug: 'android-selinux-denial-analyzer',
    title: 'Android SELinux Denial Analyzer – AVC Policy Failures',
    description: 'Find enforcing-mode SELinux avc: denied records and triage source context, target context, class and permission.',
    h1: 'Android SELinux AVC Analyzer',
    intro: 'An AVC denial is useful only when it matches the failing operation. The analyzer surfaces enforcing-mode denials and keeps them linked to boot, biometric and service failures.',
    symptoms: ['Service fails to start', 'Hardware access works only in permissive builds', 'Vendor daemon cannot open device/file/socket', 'Boot or HAL operation fails with avc: denied'],
    detects: ['SELinux avc: denied records', 'Repeated enforcing-mode denials', 'Correlation with boot/service/hardware findings'],
    checks: ['Read permission, scontext, tcontext and tclass together.', 'Match the denial timestamp to the failing operation.', 'Fix domain/file labeling or policy intentionally; do not ship permissive mode.'],
    category: 'selinux',
  },
  {
    slug: 'android-bootloop-analyzer',
    title: 'Android Bootloop Analyzer – Init, Zygote, APEX and Mount Failures',
    description: 'Inspect Android bugreports for init critical-service exits, zygote crashes, mount failures and APEX/boot initialization problems.',
    h1: 'Android Bootloop Analyzer',
    intro: 'A boot loop is usually a cascade. The first dependency that fails is more valuable than the last twenty services complaining afterward.',
    symptoms: ['Boot logo repeats', 'Boot completes only after several restarts', 'Critical service crashes during startup', 'Init/zygote/mount errors appear early'],
    detects: ['Init critical-service failures', 'Zygote crash/exits', 'Mount failures', 'APEX activation failures', 'Related storage and SELinux evidence'],
    checks: ['Find the first failed dependency.', 'Inspect storage, APEX, property and SELinux state.', 'Compare failed boot with a known-good boot from the same build.'],
    category: 'boot',
  },
];
