export interface ErrorReference {
  slug: string;
  title: string;
  description: string;
  signature: string;
  meaning: string;
  nextSteps: string[];
  subsystem: string;
}

export const errorReferences: ErrorReference[] = [
  {
    slug: 'system-server-watchdog',
    title: 'Android system_server Watchdog Timeout',
    description: 'What system_server watchdog evidence means and what to inspect before blaming the watchdog itself.',
    signature: 'WATCHDOG KILLING SYSTEM PROCESS / system_server watchdog timeout',
    meaning: 'A monitored system_server thread, service, or lock failed to make progress inside the watchdog deadline. The watchdog is the recovery mechanism; the blocked dependency immediately before it is usually more important than the kill line.',
    nextSteps: ['Identify the first overdue monitor or blocked thread.', 'Inspect binder state, lock ownership, storage latency, and kernel stalls at the same time.', 'Correlate vendor-service, display, and HAL failures that started before the watchdog fired.'],
    subsystem: 'Framework / system_server',
  },
  {
    slug: 'fatal-signal-native-crash',
    title: 'Android Fatal Signal Native Crash',
    description: 'Interpret fatal signal records, abort messages, fault addresses, and tombstone evidence in native Android crashes.',
    signature: 'Fatal signal 6 (SIGABRT) / Fatal signal 11 (SIGSEGV) / tombstone',
    meaning: 'A native process received a fatal signal. SIGABRT often carries an intentional abort message; SIGSEGV or SIGBUS usually requires fault-address, memory-map, and exact-build symbol context. The one-line fatal-signal message is not enough for source-level diagnosis.',
    nextSteps: ['Open the matching tombstone and identify process, thread, signal, abort message, and fault address.', 'Symbolize with binaries or symbols from the exact build/BuildId.', 'Review logcat immediately before the crash for the initiating failure.'],
    subsystem: 'Native runtime',
  },
  {
    slug: 'input-dispatching-timed-out',
    title: 'Android Input Dispatching Timed Out',
    description: 'Understand input-dispatch ANRs and separate blocked application work from system-wide pressure.',
    signature: 'Input dispatching timed out',
    meaning: 'The focused target did not complete input handling in time. A busy or blocked main thread is common, but binder waits, CPU starvation, storage stalls, and system_server latency can produce the same user-visible ANR.',
    nextSteps: ['Inspect the matching ANR trace and the application main thread.', 'Look for monitor, binder, I/O, or long-running work on the blocked path.', 'Check CPU, PSI, lmkd, binder, and system_server evidence at the same timestamp.'],
    subsystem: 'ActivityManager / Input',
  },
  {
    slug: 'lmkd-process-kill',
    title: 'Android lmkd Low-Memory Kill',
    description: 'How to distinguish low-memory process reclamation from an application crash or unexplained process death.',
    signature: 'lmkd: Kill / lowmemorykiller / Killing ... to free',
    meaning: 'Android reclaimed one or more processes because memory pressure crossed configured policy thresholds. A kill can be expected under pressure; repeated foreground-adjacent kills or kills that line up with user-visible failures deserve deeper memory analysis.',
    nextSteps: ['Identify the killed process, oom_adj/oom_score_adj, and available memory around the event.', 'Inspect PSI memory pressure and dumpsys meminfo rather than free-RAM alone.', 'Check whether repeated service restarts or large native allocations are creating sustained pressure.'],
    subsystem: 'Memory / lmkd',
  },
  {
    slug: 'out-of-memory-error',
    title: 'Android OutOfMemoryError / Allocation Failure',
    description: 'Interpret Java heap, native allocation, and kernel OOM evidence without mixing different memory failure classes.',
    signature: 'java.lang.OutOfMemoryError / lowmemorykiller / Out of memory: Kill process',
    meaning: 'The process or system failed to satisfy an allocation. Java heap exhaustion, native heap growth, graphics buffers, kernel memory pressure, and system-wide OOM are different failure paths and require different evidence.',
    nextSteps: ['Determine whether the failure is Java heap, native heap, graphics, or kernel/system-wide.', 'Compare process memory with dumpsys meminfo and nearby lmkd/PSI events.', 'For recurring failures, capture heap/native allocation evidence from the exact workload.'],
    subsystem: 'Memory',
  },
  {
    slug: 'failed-binder-transaction',
    title: 'FAILED BINDER TRANSACTION',
    description: 'Triage Binder IPC failures and determine whether the transaction or a dead/stalled service is the real problem.',
    signature: 'FAILED BINDER TRANSACTION / binder transaction failed / binder_alloc',
    meaning: 'A Binder IPC could not be completed. Causes include transaction-buffer pressure, target process death, blocked service threads, or invalid/oversized IPC behavior. The failure should be correlated with sender, target, and earlier service events.',
    nextSteps: ['Inspect binder failed-transaction diagnostics when present in the bugreport.', 'Identify sender and target processes and check whether the target died first.', 'If ANR/watchdog occurs nearby, inspect binder thread-pool saturation and blocked server threads.'],
    subsystem: 'Binder IPC',
  },
  {
    slug: 'transaction-too-large-exception',
    title: 'Android TransactionTooLargeException',
    description: 'Understand oversized Binder transactions and fix the payload instead of retrying an unstable IPC.',
    signature: 'android.os.TransactionTooLargeException',
    meaning: 'A Binder transaction exceeded practical transaction-buffer limits. Large Bundles, saved state, Intent extras, or result payloads are common causes. Retrying the same payload does not address the failure.',
    nextSteps: ['Find the call site and measure the data being marshalled.', 'Move bulk data out of Bundle/Intent IPC and pass a reference or stream instead.', 'Check whether several concurrent transactions are contributing to buffer pressure.'],
    subsystem: 'Binder IPC',
  },
  {
    slug: 'storage-io-error',
    title: 'Android Storage I/O Error',
    description: 'Investigate block-device, UFS/eMMC, filesystem, and read-only remount failures before higher-layer symptoms.',
    signature: 'I/O error, dev / Buffer I/O error / UFS timeout / mmc timeout',
    meaning: 'The kernel or storage stack reported that an operation did not complete normally. Storage faults can cascade into database errors, ANRs, boot failures, watchdogs, and service timeouts, so the earliest block-layer error matters.',
    nextSteps: ['Identify the first affected block device/partition and error before retries.', 'Inspect UFS/eMMC controller messages, filesystem state, mounts, and storaged output.', 'Correlate I/O latency with ANR/watchdog/boot failures rather than treating those as independent incidents.'],
    subsystem: 'Storage / kernel',
  },
  {
    slug: 'ext4-f2fs-filesystem-error',
    title: 'Android ext4 / F2FS Filesystem Error',
    description: 'Interpret ext4/F2FS corruption, checkpoint, and read-only remount messages in Android bugreports.',
    signature: 'EXT4-fs error / F2FS-fs ... error / Remounting filesystem read-only',
    meaning: 'The filesystem detected an integrity or I/O condition serious enough to report an error, and may switch to a protective state. The underlying cause can be media/controller failure, sudden power loss, or filesystem corruption.',
    nextSteps: ['Record the partition, inode/block details, and first filesystem error.', 'Check for block-layer errors that precede the filesystem complaint.', 'Treat read-only remount or verified-boot corruption as an integrity issue, not an application bug.'],
    subsystem: 'Filesystem',
  },
  {
    slug: 'selinux-avc-denied',
    title: 'Android SELinux avc: denied',
    description: 'Read SELinux AVC denials using source/target contexts, permission, object class, and incident timing.',
    signature: 'avc: denied { ... } scontext=... tcontext=... tclass=...',
    meaning: 'SELinux blocked an operation in enforcing mode. A denial is actionable when it lies on the failing path; unrelated vendor denials can also appear in noisy reports, so context and timing are essential.',
    nextSteps: ['Read permission, scontext, tcontext, tclass, comm, path/name, and permissive fields together.', 'Verify that the denial occurs during the failed service or hardware operation.', 'Fix labels/component behavior or a narrowly justified policy rule; do not use permissive mode as the production fix.'],
    subsystem: 'SELinux',
  },
  {
    slug: 'fingerprint-hw-unavailable',
    title: 'Android Fingerprint HW_UNAVAILABLE',
    description: 'Understand fingerprint hardware-unavailable errors across framework, HAL, binder, and UDFPS display coordination.',
    signature: 'HW_UNAVAILABLE / fingerprint hardware unavailable / fingerprint HAL died',
    meaning: 'The biometric framework cannot currently use the fingerprint hardware path. The reason can be transient service state, HAL/vendor process death, Binder failure, device-node access, or UDFPS display/HBM coordination.',
    nextSteps: ['Check fingerprint HAL/vendor-service lifecycle and Binder death records.', 'Correlate SELinux and kernel/device communication errors.', 'For UDFPS, align authentication time with SurfaceFlinger, composer/HBM, brightness, and display-driver events.'],
    subsystem: 'Biometrics / HAL',
  },
  {
    slug: 'surfaceflinger-unresponsive',
    title: 'Android SurfaceFlinger / Composer Failure',
    description: 'Investigate SurfaceFlinger stalls, composer service death, HWC errors, and kernel display faults as one pipeline.',
    signature: 'SurfaceFlinger unresponsive / composer service died / HWC error',
    meaning: 'The compositor or one of its display dependencies stopped progressing normally. The failure may be in userspace composition, vendor composer/HAL, Binder, DRM/panel driver, or a system-wide stall.',
    nextSteps: ['Check composer/HWC service health and death notifications.', 'Correlate DRM/panel/kernel messages and Binder failures.', 'See whether watchdog, UDFPS, or SystemUI failures occur after the display fault.'],
    subsystem: 'Display',
  },
  {
    slug: 'thermal-shutdown',
    title: 'Android Thermal Shutdown',
    description: 'Recognize explicit thermal emergency/shutdown evidence and avoid inferring shutdown from a high temperature alone.',
    signature: 'thermal shutdown / THERMAL_EMERGENCY / critical temperature',
    meaning: 'Thermal policy reached a critical condition and may have initiated shutdown or severe mitigation. High temperature readings without a policy transition or shutdown marker are weaker evidence.',
    nextSteps: ['Identify the thermal zone/sensor and the policy state that crossed the threshold.', 'Correlate charging, modem, CPU/GPU, camera, and display workload.', 'Confirm shutdown/reboot evidence and distinguish orderly thermal shutdown from an unrelated reset.'],
    subsystem: 'Thermal',
  },
  {
    slug: 'network-validation-failure',
    title: 'Android Network Validation / Data Stall Failure',
    description: 'Triage ConnectivityService validation, DNS, netd, Wi-Fi, and mobile data-stall evidence.',
    signature: 'validation failed / data stall / DNS failure / netd error',
    meaning: 'Android detected that a network path was not providing expected connectivity, or a network component reported repeated failure. This may be DNS, route, captive portal, modem/Wi-Fi transport, netd, or upstream connectivity rather than an app bug.',
    nextSteps: ['Identify the active transport and Network/NetId at the failure time.', 'Check DNS, routes, validation probes, netd, and Wi-Fi/modem state in the same window.', 'Separate a local interface drop from Internet/upstream validation failure.'],
    subsystem: 'Connectivity',
  },
  {
    slug: 'kernel-panic-not-syncing',
    title: 'Kernel panic - not syncing',
    description: 'Use pstore/ramoops and the first kernel fault to diagnose abrupt Android reboots caused by kernel panic.',
    signature: 'Kernel panic - not syncing',
    meaning: 'The Linux kernel entered a fatal state and could not continue. The panic line confirms the failure class; the useful root-cause evidence is usually earlier in the call trace, fault report, driver log, or watchdog/lockup sequence.',
    nextSteps: ['Prefer previous-boot pstore/ramoops/console-ramoops when available.', 'Locate the first warning/oops/fault before the final panic and preserve the full call trace.', 'Match kernel symbols/build exactly and correlate the affected driver with the user-visible trigger.'],
    subsystem: 'Kernel',
  },
  {
    slug: 'rcu-stall-hung-task',
    title: 'Android Kernel RCU Stall / Hung Task',
    description: 'Interpret RCU stalls and blocked-task warnings as progress failures that can precede watchdogs or reboots.',
    signature: 'rcu: INFO: rcu_* detected stalls / task ... blocked for more than ... seconds',
    meaning: 'A kernel task or CPU failed to make expected progress for a prolonged interval. The warning can be a precursor to system_server/watchdog symptoms because userspace also stops receiving timely service.',
    nextSteps: ['Preserve the blocked task stack and the first stall report.', 'Inspect storage, driver locks, IRQ/CPU starvation, and scheduling context.', 'Correlate userspace ANR/watchdog timestamps to determine whether they are downstream symptoms.'],
    subsystem: 'Kernel scheduling',
  },
  {
    slug: 'critical-service-bootloop',
    title: 'Android init Critical Service Bootloop',
    description: 'Investigate init critical-service crashes, repeated restarts, mount/APEX failures, and early-boot loops.',
    signature: 'init: Service ... (critical) ... / critical process ... exited / rebooting into recovery',
    meaning: 'A service required during boot is repeatedly exiting or a required mount/APEX dependency cannot be established. init may reboot or enter recovery after repeated critical failures.',
    nextSteps: ['Find the first critical service or mount/APEX failure, not the last restart message.', 'Check its crash/tombstone and SELinux/device-node dependencies.', 'Verify partitions, verified boot, and vendor/system compatibility for recently changed builds.'],
    subsystem: 'Init / boot',
  },
];
